export const words = [
  "Family Game",
  "Dice",
  "123",
  "4x",
  "Age of Reason",
  "Alternate History",
  "Campaign",
  "Card Game",
  "City Building",
  "Collectible Components",
  "Comic Book / Strip",
  "Conversation",
  "Cooperative",
  "Cube Rail",
  "Deduction",
  "Dexterity",
  "Dice",
  "Dinosaurs",
  "Drinking",
  "Educational",
  "Environmental",
  "Eurogame",
  "Expansion",
  "Family Game",
  "Fan Made",
  "Fishing",
  "Flicking",
  "Food",
  "Gay",
  "Improv",
  "Industry/Manufacturing",
  "Kickstarter",
  "Legacy",
  "Luck",
  "Math",
  "Mature / Adult",
  "Mecha",
  "Memory",
  "Miniatures",
  "Modern Warfare",
  "Movies / TV / Radio theme",
  "Nautical",
  "Negotiation",
  "Ninja's",
  "Ninjas",
  "Novel-based",
  "Party Game",
  "Print & Play",
  "Puzzle",
  "Queer",
  "RPG",
  "Racing",
  "Real-time",
  "Renaissance",
  "Resource Management",
  "Roman Empire",
  "Solo / Solitaire",
  "Tech",
  "Territory Building",
  "Theme Park",
  "Transportation",
  "Trivia",
  "Video Game Theme",
  "Wargame",
  "Werewolves",
  "Word Game",
];
